"""Self-play training-data generator for Texel tuning (dev tool, NOT shipped).

Plays our own engine against itself from the hand-written opening list at a
tiny fixed per-move budget (engine_side.py subprocesses, one per worker,
config chosen by env like every A/B harness side), records EVERY position
with the game result from White's perspective, skipping the first few
book plies. Writes an npz the tuner consumes:

    data/positions_<ts>.npz   {'fens': np.str_[N], 'results': np.float32[N]}

Data provenance: these positions are generated by OUR engine (this repo)
during this event — ORIGINALITY.md: training data is unrestricted, and
self-play data is the strongest signal anyway (research doc 02 §6.1).

Usage:
    python tools/gen_positions.py --target 60000 --workers 4 \
        --budget-ms 40 --config hand:1111 --out data/positions.npz
"""

import argparse
import os
import random
import subprocess
import sys
import time
from pathlib import Path

import chess

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))
sys.path.insert(0, str(_HERE))

from common import OPENING_FENS, MAX_PLY, adjudicate  # noqa: E402

SKIP_PLY = 4          # skip a few book plies (research doc 02 §6.1)
MIN_GAME_POS = 12     # drop degenerate/early games entirely


def play_one(proc, opening: str, rng: random.Random) -> list[tuple[str, float]]:
    """One game vs itself through the given engine_side proc.

    Returns (fen, result_from_white_pov) for every position after
    SKIP_PLY book plies; the white-pov result keys each sample."""
    board = chess.Board(opening)
    moves = []
    ply = 0
    while not board.is_game_over() and ply < MAX_PLY:
        resp = _ask(proc, board.fen())
        if resp.startswith("ERROR") or resp == "0000":
            return []                       # drop broken games entirely
        try:
            mv = chess.Move.from_uci(resp)
        except ValueError:
            return []
        if mv not in board.legal_moves:
            return []
        board.push(mv)
        moves.append(mv)
        ply += 1
    if board.is_game_over():
        result = board.result(claim_draw=True)
    else:
        result = adjudicate(board, ply)
    y = {"1-0": 1.0, "0-1": 0.0}.get(result, 0.5)

    # rebuild positions from the replay (cheap, correct)
    samples = []
    b2 = chess.Board(opening)
    for i, mv in enumerate(moves):
        if i >= SKIP_PLY:
            samples.append((b2.fen(), y))
        b2.push(mv)
    return samples


def _ask(proc, fen: str) -> str:
    if proc.poll() is not None:
        return "ERROR:side process died"
    try:
        proc.stdin.write(fen + "\n")
        proc.stdin.flush()
        return proc.stdout.readline().strip()
    except Exception:
        return "ERROR:io"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", type=int, default=60000)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--budget-ms", type=int, default=40)
    ap.add_argument("--config", default="hand:1111",
                    help="engine config:gate used for BOTH sides")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    out = args.out or (
        f"data/positions_{time.strftime('%Y%m%d_%H%M%S')}.npz")
    Path(out).parent.mkdir(parents=True, exist_ok=True)

    cfg, gate = args.config.split(":")
    env = dict(os.environ)
    env["CHESSATHON_EVAL_CONFIG"] = cfg
    env["CHESSATHON_EVAL_GATE"] = gate
    env["CHESSATHON_MOVE_BUDGET_MS"] = str(args.budget_ms)

    procs = [subprocess.Popen(
        [sys.executable, str(_HERE / "engine_side.py")],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL, text=True, env=env)
        for _ in range(args.workers)]
    try:
        rng = random.Random(args.seed)
        fens: list[str] = []
        results: list[float] = []
        games = 0
        t0 = time.monotonic()
        while len(fens) < args.target:
            for p in procs:
                if len(fens) >= args.target:
                    break
                opening = OPENING_FENS[rng.randrange(len(OPENING_FENS))]
                samples = play_one(p, opening, rng)
                if len(samples) < MIN_GAME_POS:
                    continue
                games += 1
                for fen, y in samples:
                    fens.append(fen)
                    results.append(y)
            if time.monotonic() - t0 > 3600:    # hard cap: 1 hour
                break
        elapsed = time.monotonic() - t0
        print(f"{games} games, {len(fens)} positions from "
              f"{args.workers} workers @ {args.budget_ms}ms in "
              f"{elapsed:.0f}s ({len(fens) / max(elapsed, 1e-9):.0f} pos/s)",
              file=sys.stderr)

        import numpy as np
        np.savez(out,
                 fens=np.array(fens, dtype=np.str_),
                 results=np.array(results, dtype=np.float32),
                 meta=np.array([
                     f"gen: {args.config} budget={args.budget_ms}ms "
                     f"workers={args.workers} games={games} seed={args.seed}"],
                     dtype=np.str_))
        print(f"wrote {out} ({len(fens)} positions)")
        return 0
    finally:
        for p in procs:
            try:
                p.stdin.write("quit\n")
                p.stdin.flush()
            except Exception:
                pass
            p.terminate()
            try:
                p.wait(timeout=5)
            except Exception:
                p.kill()


if __name__ == "__main__":
    sys.exit(main())