"""Texel tuning for the phase-2 evaluation (dev tool, NOT shipped).

Fits all 813 EVAL_PARAMS of engine/eval.py to self-play positions
(generated by tools/gen_positions.py) by iteratively reweighted least
squares on Texel's logistic loss:

    L = mean((sigma(s_i) - y_i)^2),   sigma(s) = 1/(1 + 10^(-s/400)),
    s_i = score of position i (White's POV, mg/eg tapered EXACTLY as
    engine/eval.py computes it), y_i = game result from White's POV.

The eval is linear in p (score = p . f with features f re-derived here to
BIT PARITY with the jitted evaluate(); the parity is verified on random
positions before anything is fitted). Each IRWLS iteration is a weighted
least-squares solve on the 813x813 normal system, accumulated in numpy
chunks (no scipy):  p += solve(G + lam*I, b), with backtracking so the
training loss never increases.

Fitted int32 weights are patched into engine/eval.py's TUNED_PARAMS marker
block (the "tuned" config default, so agent.py and SPRT side "tuned" pick
them up unchanged) and a .npy copy is written next to the data for
provenance. Both are OUR data — generated and fitted in this repo during
this event (ORIGINALITY.md: training data unrestricted; shipped weights
must be self-trained — these are).

Usage:
    python tools/gen_positions.py --target 60000 --workers 4 --budget-ms 40
    python tools/texel_tune.py --data data/positions_<ts>.npz \
        --max-pos 50000 [--init hand|tuned] [--no-patch]
"""

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

# The parity check compares against evaluate() with the FULL ungated eval:
# force hand:1111 so the engine side of the comparison is fixed regardless
# of what TUNED_PARAMS currently holds (feature extraction is p-independent;
# one consistent p is all the parity check needs).
os.environ["CHESSATHON_EVAL_CONFIG"] = "hand"
os.environ["CHESSATHON_EVAL_GATE"] = "1111"

import numpy as np  # noqa: E402

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

import chess                        # noqa: E402
from engine import board as B       # noqa: E402
from engine import eval as E        # noqa: E402  (P_*, tables, evaluate)

N_P = E.N_PARAMS
# Term-group MG/EG indices come from the P_* constants EXPLICITLY: the
# layout is mostly even=mg/odd=eg but P_PASSED_* breaks that (both 784..787
# and 788..791 are even), so never derive them arithmetically.
_TERM_MG = np.array([
    E.P_DOUBLED_MG, E.P_ISOLATED_MG,
    E.P_PASSED_MG, E.P_PASSED_MG + 1, E.P_PASSED_MG + 2, E.P_PASSED_MG + 3,
    E.P_BLOCKED_MG,
    E.P_MOB_N_MG, E.P_MOB_B_MG, E.P_MOB_R_MG, E.P_MOB_Q_MG,
    E.P_SHELTER_NEAR_MG, E.P_SHELTER_FAR_MG, E.P_OPEN_MG, E.P_KDIST_MG,
    E.P_BISHOP_PAIR_MG,
], dtype=int)
_TERM_EG = np.array([
    E.P_DOUBLED_EG, E.P_ISOLATED_EG,
    E.P_PASSED_EG, E.P_PASSED_EG + 1, E.P_PASSED_EG + 2, E.P_PASSED_EG + 3,
    E.P_BLOCKED_EG,
    E.P_MOB_N_EG, E.P_MOB_B_EG, E.P_MOB_R_EG, E.P_MOB_Q_EG,
    E.P_SHELTER_NEAR_EG, E.P_SHELTER_FAR_EG, E.P_OPEN_EG, E.P_KDIST_EG,
    E.P_BISHOP_PAIR_EG,
], dtype=int)
MG_IDXS = np.r_[np.arange(0, 6), np.arange(12, 396), _TERM_MG]
EG_IDXS = np.r_[np.arange(6, 12), np.arange(396, 780), _TERM_EG]
assert len(MG_IDXS) + len(EG_IDXS) == N_P - 1          # everything but tempo
assert len(np.intersect1d(MG_IDXS, EG_IDXS)) == 0
# material (mg+eg) is FROZEN at the hand priors by default: the material
# constants and the PST mean are collinear (shifting all squares of a
# piece's table by c and material by -c leaves the eval unchanged), so an
# unanchored joint fit drifts to degenerate splits (e.g. queen 342cp).
# Anchoring material identifies the PST mean and keeps exchange values sane
# (standard Texel practice: tune tables around fixed piece values).
FREEZE_MAT = np.arange(0, 12)


# ---------------------------------------------------------------------------
# Feature extraction — EXACT mirror of engine/eval.py evaluate() (gate 1111)
# ---------------------------------------------------------------------------

def _sq64(sq: int) -> int:
    return ((sq >> 4) << 3) + (sq & 7)


def _mirror(b: int) -> int:
    x = b & 0xFFFFFFFFFFFFFFFF
    return (((x & 0x00000000000000FF) << 56) | ((x & 0x000000000000FF00) << 40)
            | ((x & 0x0000000000FF0000) << 24) | ((x & 0x00000000FF000000) << 8)
            | ((x & 0x000000FF00000000) >> 8) | ((x & 0x0000FF0000000000) >> 24)
            | ((x & 0x00FF000000000000) >> 40) | ((x & 0xFF00000000000000) >> 56))


def _popcount(x: int) -> int:
    return bin(x & 0xFFFFFFFFFFFFFFFF).count("1")


def feature_vector(st) -> tuple[np.ndarray, int, bool]:
    """(f int64[813], phase, forced_zero) mirroring evaluate()'s pass 1+2,
    king safety, bishop pair, tempo. forced_zero = the eval's insufficient-
    material early-return fires (score forced to 0) — such positions are
    dropped from training."""
    sqr = st['squares'][0]
    side = int(st['side'][0])
    f = np.zeros(N_P, dtype=np.int64)

    phase = 0
    wp = 0
    bp = 0
    mN = mB = mR = mQ = 0
    dbl = iso = blk = 0
    passed = [0, 0, 0, 0]
    sh_near = sh_far = opn = 0
    bishops = [0, 0]
    has_pawn = has_major = False
    mins = 0

    # ---- pass 1: material + PST + phase + mobility + bitboards ----
    for sq in range(128):
        if (sq & 0x88) != 0:
            continue
        pc = int(sqr[sq])
        if pc == 0:
            continue
        t = abs(pc)
        color = 1 if pc > 0 else 0
        s = _sq64(sq) if color == 1 else _sq64(sq) ^ 56
        sign = 1 if color == 1 else -1
        f[E.P_MAT_MG + t - 1] += sign
        f[E.P_MAT_EG + t - 1] += sign
        f[E.P_PST_MG + (t - 1) * 64 + s] += sign
        f[E.P_PST_EG + (t - 1) * 64 + s] += sign
        phase += int(E.PHASE_W[t])
        if t == B.PAWN:
            has_pawn = True
            b = 1 << _sq64(sq)
            if color == 1:
                wp |= b
            else:
                bp |= b
        elif t == B.ROOK or t == B.QUEEN:
            has_major = True
            if t == B.ROOK:
                for di in range(4):
                    for k in range(8):
                        to = int(E._ROOK_RAYS[sq, di, k])
                        if to < 0:
                            break
                        q = int(sqr[to])
                        if q == 0:
                            mR += sign
                        elif (q > 0) != (pc > 0):
                            mR += sign
                            break
                        else:
                            break
            else:
                for di in range(4):
                    for k in range(8):
                        to = int(E._RAYS[sq, di, k])
                        if to < 0:
                            break
                        q = int(sqr[to])
                        if q == 0:
                            mQ += sign
                        elif (q > 0) != (pc > 0):
                            mQ += sign
                            break
                        else:
                            break
                for di in range(4):
                    for k in range(8):
                        to = int(E._ROOK_RAYS[sq, di, k])
                        if to < 0:
                            break
                        q = int(sqr[to])
                        if q == 0:
                            mQ += sign
                        elif (q > 0) != (pc > 0):
                            mQ += sign
                            break
                        else:
                            break
        elif t == B.KNIGHT:
            mins += 1
            for d in range(8):
                to = sq + int(B._KNIGHT_DELTAS[d])
                if (to & 0x88) == 0:
                    q = int(sqr[to])
                    if q == 0 or (q > 0) != (pc > 0):
                        mN += sign
        elif t == B.BISHOP:
            mins += 1
            bishops[color] += 1
            for di in range(4):
                for k in range(8):
                    to = int(E._RAYS[sq, di, k])
                    if to < 0:
                        break
                    q = int(sqr[to])
                    if q == 0:
                        mB += sign
                    elif (q > 0) != (pc > 0):
                        mB += sign
                        break
                    else:
                        break
        elif t == B.KING:
            pass

    # ---- pass 2: pawn structure ----
    wpM = _mirror(wp)
    bpM = _mirror(bp)
    for sq in range(128):
        if (sq & 0x88) != 0:
            continue
        pc = int(sqr[sq])
        if pc == 0 or abs(pc) != B.PAWN:
            continue
        s = _sq64(sq)
        if pc > 0:
            b = 1 << s
            if (wp & int(E.ADJ_SQ[s])) == 0:
                iso += 1
            rk = s >> 3
            if (bp & int(E.PASSED_W[s])) == 0:
                if 3 <= rk <= 6:
                    if (bp & (b << 8)) != 0:
                        blk += 1
                    else:
                        passed[rk - 3] += 1
        else:
            sm = s ^ 56
            bm = 1 << sm
            if (bp & int(E.ADJ_SQ[s])) == 0:
                iso -= 1
            rk = sm >> 3
            if (wpM & int(E.PASSED_W[sm])) == 0:
                if 3 <= rk <= 6:
                    if (wpM & (bm << 8)) != 0:
                        blk -= 1
                    else:
                        passed[rk - 3] -= 1
    for ff in range(8):
        c = _popcount(wp & int(E.FILE_SQ[ff]))
        if c > 1:
            dbl += c - 1
        c = _popcount(bp & int(E.FILE_SQ[ff]))
        if c > 1:
            dbl -= c - 1

    # ---- king safety + tropism ----
    wks = _sq64(int(st['kingsq'][0][B.WHITE]))
    bks = _sq64(int(st['kingsq'][0][B.BLACK]))
    kdist = max(abs((wks & 7) - (bks & 7)), abs((wks >> 3) - (bks >> 3)))
    sh_near += _popcount(wp & int(E.SHELTER_NEAR[wks]))
    sh_far += _popcount(wp & int(E.SHELTER_FAR[wks]))
    if (wp & int(E.FILE_SQ[wks])) == 0:
        opn += 1
    bksm = bks ^ 56
    sh_near -= _popcount(bpM & int(E.SHELTER_NEAR[bksm]))
    sh_far -= _popcount(bpM & int(E.SHELTER_FAR[bksm]))
    if (bp & int(E.FILE_SQ[bks])) == 0:
        opn -= 1

    # ---- assemble feature groups ----
    f[E.P_DOUBLED_MG] = f[E.P_DOUBLED_EG] = dbl
    f[E.P_ISOLATED_MG] = f[E.P_ISOLATED_EG] = iso
    f[E.P_BLOCKED_MG] = f[E.P_BLOCKED_EG] = blk
    f[E.P_PASSED_MG:E.P_PASSED_MG + 4] = passed
    f[E.P_PASSED_EG:E.P_PASSED_EG + 4] = passed
    f[E.P_MOB_N_MG] = f[E.P_MOB_N_EG] = mN
    f[E.P_MOB_B_MG] = f[E.P_MOB_B_EG] = mB
    f[E.P_MOB_R_MG] = f[E.P_MOB_R_EG] = mR
    f[E.P_MOB_Q_MG] = f[E.P_MOB_Q_EG] = mQ
    f[E.P_SHELTER_NEAR_MG] = f[E.P_SHELTER_NEAR_EG] = sh_near
    f[E.P_SHELTER_FAR_MG] = f[E.P_SHELTER_FAR_EG] = sh_far
    f[E.P_OPEN_MG] = f[E.P_OPEN_EG] = opn
    f[E.P_KDIST_MG] = f[E.P_KDIST_EG] = kdist
    bpw = bishops[B.WHITE]
    bpb = bishops[B.BLACK]
    bp_val = (1 if bpw >= 2 else 0) - (1 if bpb >= 2 else 0)
    f[E.P_BISHOP_PAIR_MG] = f[E.P_BISHOP_PAIR_EG] = bp_val
    # Tempo is CONSTANT +1 in White-POV terms: evaluate() returns the
    # side-to-move value ±(SB+10) (black STM negates the whole thing
    # including tempo), so the White-POV score is SB + 10 regardless of
    # the side to move; engine == model(white) iff f[P_TEMPO] == +1.
    f[E.P_TEMPO] = 1

    forced_zero = (not has_pawn and not has_major and mins <= 1)
    return f, phase, forced_zero


def score_white(f: np.ndarray, phase: int, p: np.ndarray) -> int:
    """White-POV score, bit-exact with evaluate() (gate 1111): the eval's
    tempo sign convention is folded into f[P_TEMPO] (side to move)."""
    mg = int(f[MG_IDXS] @ p[MG_IDXS])
    eg = int(f[EG_IDXS] @ p[EG_IDXS])
    if phase > E.MAX_PHASE:
        phase = E.MAX_PHASE
    return (mg * phase + eg * (E.MAX_PHASE - phase)) // E.MAX_PHASE \
        + int(f[E.P_TEMPO]) * int(p[E.P_TEMPO])


# ---------------------------------------------------------------------------
# Parity + gradient checks vs the jitted engine
# ---------------------------------------------------------------------------

def _parity_fens() -> list[str]:
    fens = [
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "r2q1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 8",
        "k7/8/2P5/8/8/8/8/K7 w - - 0 1",
        "k7/2p5/3p4/8/8/4P3/1P6/7K w - - 0 1",
        "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
        "4k3/8/8/8/8/8/8/4K3 w - - 0 1",            # insufficient (KvK)
        "8/5k2/8/4P3/8/3K4/8/8 w - - 0 1",          # KPK
        "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1",
        "8/8/8/8/8/8/2p5/K7 b - - 0 1",            # passed BLACK pawn 6th-ish
        "k7/8/8/8/8/8/PPP5/1K6 w - - 0 1",         # shelter
    ]
    # random-walk FENs (both colors, full feature coverage)
    rng = np.random.default_rng(1234)
    for _ in range(40):
        board = chess.Board()
        for _ply in range(int(rng.integers(20, 90))):
            legal = list(board.legal_moves)
            if not legal:
                break
            board.push(legal[int(rng.integers(len(legal)))])
        fens.append(board.fen())
    return fens


def check_parity(p: np.ndarray, n: int = 60) -> None:
    """score_white(feature_vector(st)) must equal evaluate(st) EXACTLY."""
    fens = _parity_fens()[:n]
    bad = 0
    for fen in fens:
        st = B.parse_fen(fen)
        f, phase, forced_zero = feature_vector(st)
        if forced_zero:
            assert E.evaluate(st) == 0, fen
            continue
        s = score_white(f, phase, p)
        ev = int(E.evaluate(st))
        # evaluate() is STM-perspective; score_white is White-POV
        expect = ev if int(st['side'][0]) == B.WHITE else -ev
        if s != expect:
            bad += 1
            print(f"PARITY FAIL {fen}: model={s} engine={expect}")
    assert bad == 0, f"{bad}/{len(fens)} parity failures"
    print(f"parity OK on {len(fens)} positions (engine==model, exact)")


def check_gradient(p: np.ndarray, fens: list[str]) -> float:
    """Finite-diff check of the analytic loss gradient (informational)."""
    y = 0.7
    f, phase, _ = feature_vector(B.parse_fen(fens[0]))
    dln = np.log(10.0) / 400.0
    # integer h is exact in score_white; floor noise ~1cp is negligible vs h
    h = 100.0
    idxs = np.array([0, 1, 2, 3, 4, 5,          # material mg
                     E.P_MOB_N_MG, E.P_TEMPO], dtype=int)

    def loss_at(pv):
        s0 = score_white(f, phase, pv)
        sig = 1.0 / (1.0 + 10.0 ** (-s0 / 400.0))
        return (sig - y) ** 2

    numeric = np.zeros(len(idxs))
    for k, i in enumerate(idxs):
        d = np.zeros(N_P)
        d[i] = h
        numeric[k] = (loss_at(p + d) - loss_at(p - d)) / (2 * h)

    sig = 1.0 / (1.0 + 10.0 ** (-score_white(f, phase, p) / 400.0))
    analytic = np.zeros(len(idxs))
    for k, i in enumerate(idxs):
        fl = (phase / E.MAX_PHASE) if i in MG_IDXS else \
            ((E.MAX_PHASE - phase) / E.MAX_PHASE if i in EG_IDXS else 1.0)
        analytic[k] = 2 * (sig - y) * sig * (1 - sig) * dln * f[i] * fl
    return float(np.max(np.abs(numeric - analytic)))


# ---------------------------------------------------------------------------
# Data loading + featurization
# ---------------------------------------------------------------------------

def load_data(path: Path, max_pos: int, seed: int):
    d = np.load(path, allow_pickle=True)
    fens = d["fens"].astype(str)
    results = d["results"].astype(np.float64)
    if max_pos and len(fens) > max_pos:
        rng = np.random.default_rng(seed)
        idx = rng.choice(len(fens), max_pos, replace=False)
        fens = fens[idx]
        results = results[idx]
    print(f"loaded {len(fens)} positions from {path}")
    return fens, results


def featurize(fens: np.ndarray):
    """CSR arrays (rows, cols, vals) + phases + keep-mask (drops
    insufficient-material positions whose eval score is forced 0)."""
    rows = []
    cols = []
    vals = []
    phases = np.zeros(len(fens), dtype=np.int32)
    drop = []
    t0 = time.monotonic()
    for i, fen in enumerate(fens):
        st = B.parse_fen(fen)
        f, phase, forced_zero = feature_vector(st)
        if forced_zero:
            drop.append(i)
            continue
        nz = np.nonzero(f)[0]
        rows.append(np.full(len(nz), i, dtype=np.int32))
        cols.append(nz.astype(np.int32))
        vals.append(f[nz].astype(np.int64))
        phases[i] = phase
    rows = np.concatenate(rows)
    cols = np.concatenate(cols)
    vals = np.concatenate(vals)
    keep = np.setdiff1d(np.arange(len(fens)), np.array(drop))
    print(f"featurized {len(fens)} positions in {time.monotonic() - t0:.1f}s "
          f"({len(rows)} nnz, {len(drop)} insufficient-material dropped)")
    return rows, cols, vals, phases[keep], keep


# ---------------------------------------------------------------------------
# IRWLS on the logistic loss (chunked, numpy-only)
# ---------------------------------------------------------------------------

def _blocks(n: int, size: int = 2048):
    for i0 in range(0, n, size):
        yield i0, min(i0 + size, n)


def fit_irwls(rows, cols, vals, phases, y, init, iters=8, lam=1e-3,
              block=2048, seed=7, freeze=FREEZE_MAT):
    p = np.array(init, dtype=np.float64)
    n = len(y)
    free = np.setdiff1d(np.arange(N_P), freeze) if freeze is not None \
        else np.arange(N_P)
    rng = np.random.default_rng(seed)
    val_idx = rng.choice(n, max(1, n // 20), replace=False)
    tr_idx = np.setdiff1d(np.arange(n), val_idx)
    s_all = np.zeros(n)
    dln = np.log(10.0) / 400.0

    def one_block(i0, i1, pv):
        """Dense design matrix block (n_block x N_P) + engine-exact scores."""
        m = (rows >= i0) & (rows < i1)
        X = np.zeros((i1 - i0, N_P))
        np.add.at(X, (rows[m] - i0, cols[m]), vals[m])
        ph = np.minimum(phases[i0:i1], E.MAX_PHASE).astype(np.float64)
        mg = X[:, MG_IDXS] @ pv[MG_IDXS]
        eg = X[:, EG_IDXS] @ pv[EG_IDXS]
        s = (np.floor((mg * ph + eg * (E.MAX_PHASE - ph)) / E.MAX_PHASE)
             + X[:, E.P_TEMPO] * pv[E.P_TEMPO])
        return X, s, ph

    def full_pass(pv):
        for i0, i1 in _blocks(n, block):
            _, s, _ = one_block(i0, i1, pv)
            s_all[i0:i1] = s

    def losses():
        sig = 1.0 / (1.0 + 10.0 ** (-s_all / 400.0))
        return (float(np.mean((sig[tr_idx] - y[tr_idx]) ** 2)),
                float(np.mean((sig[val_idx] - y[val_idx]) ** 2)))

    full_pass(p)
    tr_l, va_l = losses()
    print(f"iter  0 train {tr_l:.6f} val {va_l:.6f}")

    for it in range(1, iters + 1):
        sig_all = 1.0 / (1.0 + 10.0 ** (-s_all / 400.0))
        resid = sig_all - y
        G = np.zeros((N_P, N_P))
        b = np.zeros(N_P)
        for i0, i1 in _blocks(n, block):
            X, s, ph = one_block(i0, i1, p)
            sig = sig_all[i0:i1]
            sd = dln * sig * (1.0 - sig)
            w = sd ** 2
            z = s + resid[i0:i1] / (sd + 1e-12)
            rw = w * (z - s)
            Xs = X.copy()
            Xs[:, EG_IDXS] *= (E.MAX_PHASE - ph)[:, None] / E.MAX_PHASE
            Xs[:, MG_IDXS] *= ph[:, None] / E.MAX_PHASE
            G += Xs.T @ (Xs * w[:, None])
            b += Xs.T @ rw
        G += np.eye(N_P) * lam
        Gf = G[free][:, free]
        bf = b[free]
        try:
            delta_f = np.linalg.solve(Gf, bf)
        except np.linalg.LinAlgError:
            delta_f = np.linalg.lstsq(Gf, bf, rcond=None)[0]
        delta = np.zeros(N_P)
        delta[free] = delta_f

        step = 1.0
        while step > 1e-4:
            cand = p - step * delta
            full_pass(cand)
            tr_c, va_c = losses()
            if tr_c <= tr_l + 1e-9:
                p = cand
                tr_l, va_l = tr_c, va_c
                break
            step *= 0.5
        if step <= 1e-4:
            raise RuntimeError("IRWLS step failed to reduce training loss")
        print(f"iter {it:2d} train {tr_l:.6f} val {va_l:.6f} "
              f"step {step:.2f} max|dp| {np.max(np.abs(delta * step)):.1f}")
    return p


# ---------------------------------------------------------------------------
# Patch TUNED_PARAMS into engine/eval.py
# ---------------------------------------------------------------------------

def format_params(p: np.ndarray) -> str:
    p = np.rint(p).astype(np.int64)
    lines = ["TUNED_PARAMS = np.array(["]
    for i in range(0, N_P, 12):
        lines.append("    " + ", ".join(f"{int(v):6d}" for v in p[i:i + 12])
                     + ",")
    lines.append("], dtype=np.int32)")
    return "\n".join(lines)


def patch_eval_py(p: np.ndarray) -> str:
    path = _HERE.parent / "engine" / "eval.py"
    src = path.read_text()
    start = src.index("# >>> TUNED_PARAMS_BLOCK >>>")
    end = src.index("# <<< TUNED_PARAMS_BLOCK <<<")
    marker_end = src.index("\n", start) + 1
    new = src[:marker_end] + format_params(p) + "\n" + src[end:]
    path.write_text(new)
    return str(path)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", required=True)
    ap.add_argument("--max-pos", type=int, default=0)
    ap.add_argument("--iters", type=int, default=8)
    ap.add_argument("--lam", type=float, default=1e-3)
    ap.add_argument("--init", default="tuned",
                    help="hand|tuned start point (tuned==hand pre-tuning)")
    ap.add_argument("--no-patch", action="store_true")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    np.set_printoptions(linewidth=160)
    init = (np.array(E.HAND_PARAMS, dtype=np.float64) if args.init == "hand"
            else np.array(E.TUNED_PARAMS, dtype=np.float64))
    print(f"init: {args.init} (N_PARAMS={N_P})")

    # 1. structural validation: feature extraction vs the jitted engine
    hand = np.array(E.HAND_PARAMS, dtype=np.float64)
    check_parity(hand, 60)
    maxg = check_gradient(hand, _parity_fens())
    print(f"gradient finite-diff |max diff|: {maxg:.2e}")
    if maxg > 1.0:
        print("WARNING: analytic gradient deviates (floor noise is <1cp; "
              "this should be tiny)")

    # 2. load + featurize
    fens, results = load_data(Path(args.data), args.max_pos, args.seed)
    rows, cols, vals, phases, keep = featurize(fens)
    y = results[keep]
    print(f"fitting on {len(y)} positions, {N_P} params, "
          f"sparsity {len(rows) / (len(y) * N_P):.4f}")

    # 3. IRWLS
    p = fit_irwls(rows, cols, vals, phases, y, init,
                  iters=args.iters, lam=args.lam, seed=args.seed)

    # 4. report
    pint = np.rint(p).astype(np.int64)
    pinit = np.rint(init).astype(np.int64)
    print("\n== fitted params (rounded to int) ==")
    print("material mg :", pint[E.P_MAT_MG:E.P_MAT_MG + 6])
    print("material eg :", pint[E.P_MAT_EG:E.P_MAT_EG + 6])
    print("passed mg   :", pint[E.P_PASSED_MG:E.P_PASSED_MG + 4])
    print("passed eg   :", pint[E.P_PASSED_EG:E.P_PASSED_EG + 4])
    print("doub/iso/blk mg:", pint[[E.P_DOUBLED_MG, E.P_ISOLATED_MG,
                                    E.P_BLOCKED_MG]])
    print("mob N/B/R/Q mg:", pint[[E.P_MOB_N_MG, E.P_MOB_B_MG,
                                   E.P_MOB_R_MG, E.P_MOB_Q_MG]])
    print("shelter n/f mg, open mg:",
          pint[[E.P_SHELTER_NEAR_MG, E.P_SHELTER_FAR_MG, E.P_OPEN_MG]])
    print("kdist mg/eg :", pint[[E.P_KDIST_MG, E.P_KDIST_EG]])
    print("bishop pr mg/eg:", pint[[E.P_BISHOP_PAIR_MG, E.P_BISHOP_PAIR_EG]])
    print("tempo       :", pint[E.P_TEMPO])
    chg = np.abs(pint - pinit)
    print(f"max |delta| vs init: {chg.max()}  mean: {chg.mean():.1f}  "
          f"params changed: {(chg > 2).sum()}/{N_P}")

    # 5. provenance + optional patch + verification
    out_npy = Path(args.data).parent / \
        f"tuned_params_{time.strftime('%Y%m%d_%H%M%S')}.npy"
    np.save(out_npy, pint)
    print(f"saved weights: {out_npy}")
    if not args.no_patch:
        target = patch_eval_py(pint)
        print(f"patched TUNED_PARAMS into {target}")
        env = dict(os.environ)
        env["PYTHONPATH"] = str(_HERE.parent)
        r = subprocess.run([sys.executable,
                            str(_HERE.parent / "engine" / "eval.py")],
                           capture_output=True, text=True, env=env,
                           cwd=str(_HERE.parent))
        print(r.stdout.strip() or r.stderr.strip())
        if r.returncode != 0:
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())